#!/usr/bin/env bash
# Configures localhost and facebook.com resolution in /etc/hosts safely in Docker


sed 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' /etc/hosts > /tmp/hosts_temp

if ! grep -q "facebook.com" /tmp/hosts_temp; then
    echo "8.8.8.8 facebook.com" >> /tmp/hosts_temp
else
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' /tmp/hosts_temp
fi

cat /tmp/hosts_temp > /etc/hosts

rm /tmp/hosts_temp
